version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: microservicio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d microservicio"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build:
      context: C:/Users/User/Desktop/ProbarSiVale/Discovery/discovery
      dockerfile: Dockerfile
    container_name: eureka_server
    ports:
      - "8761:8761"
    environment:
      SPRING_APPLICATION_NAME: eureka-server
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://eureka-server:8761/"] 
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: C:/Users/User/Desktop/ProbarSiVale/gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: api-gateway
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SERVER_PORT: 8080

  ordenes:
    build:
      context: ./ordenes
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: ordenes
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/microservicio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      MAVEN_OPTS: "-DskipTests"

  productos:
    build:
      context: ./productos
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: productos
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/microservicio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      MAVEN_OPTS: "-DskipTests"

  stock:
    build:
      context: ./stock
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: stock
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/microservicio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      MAVEN_OPTS: "-DskipTests"

  usuarios:
    build:
      context: ./usuarios
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: usuarios
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/microservicio
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      MAVEN_OPTS: "-DskipTests"

volumes:
  postgres_data:
